version: '3.3'
services:
    cloud-torrent:
#        network_mode: host
        ports:
            - '80:80'
#            - '50007:50007'
        volumes:
            - '/app/downloads:/downloads'
            - '/app/torrents:/torrents'
            - '/app/config:/etc/cloud-torrent'
        image: boypt/cloud-torrent
        command: --auth username:password
