name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        clean: false
        submodules: 'recursive'
    - run: |
        git fetch --prune --unshallow --tags

    - name: Upload binary files (linux_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: simple-torrent_linux_amd64
        path: release/simple-torrent*linux_amd64.*

    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: simple-torrent_linux_arm
        path: release/simple-torrent*linux_arm.*

    - name: Upload binary files (linux_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: simple-torrent_linux_arm64
        path: release/simple-torrent*linux_arm64.*
