name: Go
on:
  push:
    tags:
    - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        clean: false
        submodules: 'recursive'
    - run: |
        git fetch --prune --unshallow --tags
        
    - name: Get dependencies and build
      run: |
        go get github.com/rakyll/statik
        export PATH=$PATH:~/go/bin/
        statik -src=models -f
        sudo apt-get update
        sudo apt-get -y install gcc-mingw-w64-x86-64
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        chmod +x ./build.sh
        ./build.sh -r b
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'

    - name: Generate Git log
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        echo "Current Tag: ${GITHUB_REF}"
        git checkout ${GITHUB_REF} -b compile
        GITVER=$(git describe --tags)
        PREVVER=$(git describe --tags --abbrev=0 ${GITVER}~1)
        git log --oneline ${PREVVER}..${GITVER} > gittaglogs.txt
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: |
        bash scripts/make_release.sh gzip amd64
        bash scripts/make_release.sh gzip amd64 purego
        bash scripts/make_release.sh gzip arm64 purego
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          cloud-torrent_linux_amd64.gz
          cloud-torrent_linux_amd64_static.gz
          cloud-torrent_linux_arm64_static.gz
        prerelease: true
        draft: false
        body_path: gittaglogs.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
